### ISSUE TITLE
Gokrazy supervisor keeps restarting process if manually started

### ISSUE THREAD

**Issue by joneskoo** [gokrazy/gokrazy#117]
## Platform

I’m using:

* [ ] gokrazy/rpi3b
* [x] gokrazy/rpi3b+
* [ ] gokrazy/rpi4b
* [ ] gokrazy/apu2c4
* [ ] gokrazy/x86-64

## Observed behavior

As in tailscale/tailscale#4117. If a service implements gokrazy exit code 125 on GOKRAZY_FIRST_START=1, and the user starts the process anyway from console, it keeps being restarted even if it keeps failing in a loop.

## Expected behavior

Do not supervise and keep restarting process if it has reported code 125 on first start. That is, remember that process doesn't want to be supervised if it returns 125 and only start once.

**Comment by stapelberg** [comment]
Alternatively, we could also reset GOKRAZY_FIRST_START to 1 when the user restarts a service, right?

**Comment by joneskoo** [comment]
Good idea, no reason to not set the first start on every new start, including manual. Simple and compatible extension of the interface.

**Comment by stapelberg** [comment]
Cool. Do you want to send a pull request or would you prefer if I did the change?

**Comment by joneskoo** [comment]
I don't mind at all if you implement it. I've been working/procrastinating on appliance refresh during my vacation but the rest of the vacation is more busy.

**Comment by stapelberg** [comment]
Turns out we can’t implement it like that after all, because that breaks `breakglass`.

**Comment by stapelberg** [comment]
I suppose the best way would be to remove the “restart” button in favor of a “run once” and “supervise (run in a loop)” button.

`gok run` also would ideally run just once by default (currently runs in a loop).
