### ISSUE TITLE
Replacement module logic always assumes local replacement

### ISSUE THREAD

**Issue by andig** [gokrazy/gokrazy#148]
Replacement modules, when generating the go.mod for the build, seem to assume a local replacement:

```
[building (go compiler)]2022/10/05 13:14:06 Migrated go.mod to builddir/github.com/gokrazy/kernel/go.mod, see https://gokrazy.org/development/modules/
go: errors parsing go.mod:
/Users/andig/htdocs/evcc/builddir/github.com/gokrazy/kernel/go.mod:196: replacement module directory path "/Users/andig/htdocs/evcc/github.com/andig/go-powerwall" cannot have version
```

In this case, the replacement is an actual module, not a local path:

    replace github.com/foogod/go-powerwall => github.com/andig/go-powerwall v0.2.1-0.20220205120646-e5220ad9a9a0

**Comment by stapelberg** [comment]
Thanks, should probably be a quick fix, but it might be a few days until I can implement it.
