### ISSUE TITLE
Automate creating user partition

### ISSUE THREAD

**Issue by andig** [gokrazy/gokrazy#150]
When I last used gokrazy, creating the user partition was cumbersome and involved using loopback devices. This is painful on MacOS and in Docker, both. I've noticed that the `gokr-packr` now advertises to do this without loopback:

     /sbin/mkfs.ext4 evcc_0.105.1.image -F -E offset=1157627904

This seems possible inside Docker. To automate the process, it would be nice if this step could be included in the build process, maybe by adding a command line parameter for a Golang template like:

    --userdata "mkfs.ext4 {{ .Image }} -F -E offset={{ .Offset }}"

That would allow running automated builds even in CI and Docker without additional manual steps or parsing the `gokr-packr` output.

Alternative approaches:

If the offset could potentially be obtained _after_ creating the image it would also suffice to be able to print the offset alone as it's the magic constant determining the location of the user partition. It might also be an idea to specify a file for writing the offset to if it cannot be determined after creating the image.

**Comment by stapelberg** [comment]
I have good news for you: https://github.com/gokrazy/mkfs. Does that fit your use-case?

**Comment by andig** [comment]
Wow. It just got even crazier than when I discovered WPA Wifi ;)

**Comment by stapelberg** [comment]
> Wow. It just got even crazier than when I discovered WPA Wifi ;)

Let me make you aware of https://github.com/gokrazy/gokrazy/issues/147, then, which is another big development (still in progress) :)
