### ISSUE TITLE
Document ExtraFilePaths relative path base

### ISSUE THREAD

**Issue by bradfitz** [gokrazy/gokrazy#195]
The docs at https://gokrazy.org/userguide/instance-config/ say:

> ExtraFilePaths is a map from root file system destination path (e.g. /etc/caddy/Caddyfile) to a relative or absolute path of the extra files to include.

But it doesn't clarify what it's relative _to_.

Relative to the current directory of the person running `gok`? Relative to the config file? The latter would be my preference, especially along with #194. Then I can run `gok -i foo ...` from anywhere in my git repo and get predictable behavior for how the relative file paths are resolved.

**Comment by stapelberg** [comment]
It’s relative to the instance directory (which contains the config.json). Clarified in commit https://github.com/gokrazy/gokrazy/commit/587aeb8c2ca7a24b29e37f5efe7e5ff25f11a1b0
