### ISSUE TITLE
useful go command tools

### ISSUE THREAD

**Issue by gedw99** [gokrazy/gokrazy#20]
https://github.com/jnjackins/cmd

Might be good for gokracy. i use these everywhere

**Comment by stapelberg** [comment]
Thanks for the hint. These look useful indeed, but not specifically for gokrazy itself: there is no interactive environment in gokrazy, and none is planned. It might come in handy in combination with https://github.com/gokrazy/breakglass, though.

**Comment by joeblew99** [comment]
I use it because I need to provide a CLI that works on windows as well as everywhere else. Saved me lots of hassle
