### ISSUE TITLE
DNS bug that only get fixes whe  manualy stop and start service from the UI

### ISSUE THREAD

**Issue by BrunoTeixeira1996** [gokrazy/gokrazy#214]
## Platform

I’m using:

* [ ] gokrazy/rpi3b
* [ ] gokrazy/rpi3b+
* [x] gokrazy/rpi4b
* [ ] gokrazy/apu2c4
* [ ] gokrazy/x86-64

## Observed behavior

I am using [rssole](https://github.com/TheMightyGit/rssole) in gokrazy.
I used this for a couple of months now and everything runs just fine.
Yesterday I was playing with `HTTPPort` in gokrazy and modified to `9999` and then to `80` and everything works again just fine but now for some reason rssole does not work.

I don't think this is rssole problem because I ran in 2 different machines the same code and everything works but in gokrazy I am having a DNS error

```
time=1970-01-01T01:00:03.167+01:00 level=ERROR msg="update failed" feed=https://github.com/gokrazy/gokrazy/releases.atom error="rss parseurl https://github.com/gokrazy/gokrazy/releases.atom Get \"https://github.com/gokrazy/gokrazy/releases.atom\": dial tcp: lookup github.com on [::1]:53: read udp [::1]:57250->[::1]:53: read: connection refused"
time=1970-01-01T01:00:03.167+01:00 level=ERROR msg="update failed" feed=https://github.com/Simpsonpt/AppSecEzine/commits.atom error="rss parseurl https://github.com/Simpsonpt/AppSecEzine/commits.atom Get \"https://github.com/Simpsonpt/AppSecEzine/commits.atom\": dial tcp: lookup github.com on [::1]:53: read udp [::1]:57250->[::1]:53: read: connection refused"
time=1970-01-01T01:00:03.167+01:00 level=ERROR msg="update failed" feed=https://emacsredux.com/atom.xml error="rss parseurl https://emacsredux.com/atom.xml Get \"https://emacsredux.com/atom.xml\": dial tcp: lookup emacsredux.com on [::1]:53: read udp [::1]:58897->[::1]:53: read: connection refused"
time=1970-01-01T01:00:03.165+01:00 level=ERROR msg="update failed" feed=https://github.com/TheMightyGit/rssole/releases.atom error="rss parseurl https://github.com/TheMightyGit/rssole/releases.atom Get \"https://github.com/TheMightyGit/rssole/releases.atom\": dial tcp: lookup github.com on [::1]:53: read udp [::1]:57250->[::1]:53: read: connection refused"
time=1970-01-01T01:00:03.168+01:00 level=ERROR msg="update failed" feed=https://news.ycombinator.com/rss error="rss parseurl https://news.ycombinator.com/rss Get \"https://news.ycombinator.com/rss\": dial tcp: lookup news.ycombinator.com on [::1]:53: read udp [::1]:43157->[::1]:53: read: connection refused"
```
Meaning I am having connection refused.
If I stop and start manualy in gokrazy UI everything works fine.

The following is an excerpt of resolv.conf (192.168.30.1 is my router)

```
/tmp/breakglass3283346272 # cat /etc/resolv.conf
# generated by gokrazy/dhcp
domain home
search home
nameserver 192.168.30.1
```

## Expected behavior

When using rssole everything worked but then after playing with HTTPPorts in gokrazy config it stoped working as intended.

**Comment by stapelberg** [comment]
Here’s a guess: probably rssole is started before the DNS resolver is obtained via DHCP. If rssole does not re-read `/etc/resolv.conf` after its first read, that would explain the symptom.

You can try setting the [`WaitForClock` option](https://gokrazy.org/userguide/instance-config/#packagewaitforclock), which not only waits for the clock, but also for the network to be up (because the network is needed to synchronize the clock).

A different fix would be to ship a DNS forwarder with gokrazy so that `/etc/resolv.conf` can start out with `nameserver localhost` and then eventually queries start working, but that sounds like a lot of effort and cost compared to just starting the affected program(s) later in the boot sequence :)

**Comment by BrunoTeixeira1996** [comment]
Yes , `WaitForClock` works fine. however rssole self updates after a couple of seconds so it will work after the first update
