### ISSUE TITLE
When running `gok edit` the `$EDITOR` should be launched via a shell

### ISSUE THREAD

**Issue by stv0g** [gokrazy/gokrazy#217]
In my environment `$EDITOR` is set to `code -w` which is not supported by gok as its spawning the editor as a subcommand rather than starting it in a shell.

I failed to find any spec on how `$EDITOR` should be interpreted. However, I think we can try to imitate the behaviour of Git which is spawning it in a shell:

https://github.com/git/git/blob/94e83dcf5b5faaa22e32729305f8fd7090bfdfed/editor.c#L91

**Comment by stapelberg** [comment]
Thanks! This is fixed with commit https://github.com/gokrazy/tools/commit/231dea4b57042ff090c0a94fa03abe1dab9e3a3f
