### ISSUE TITLE
Mount namespaces?

### ISSUE THREAD

**Issue by stv0g** [gokrazy/gokrazy#218]
The gokrazy documentation says:

> [unshare(CLONE_NEWNS)](https://manpages.debian.org/unshare.2) is used so that each process operates in its own [mount namespace](https://manpages.debian.org/mount_namespaces.7).

However, while reading the gokrazy code I was unable to find any invocation of `unshare`.

Is the documentation outdated? Or I am just missing the relevant piece of code here?

I started to look into that code because I was wondering how we can do IPC between the started Go modules. E.g. via unix domain sockets on a common mount point.

**Comment by stapelberg** [comment]
The documentation was outdated; the behavior changed in https://github.com/gokrazy/gokrazy/commit/d2987c246916f481557ee940f7ef73e876629b77. It’s now updated. Thanks for the hint!
