### ISSUE TITLE
Feature Request: API for Gokrazy

### ISSUE THREAD

**Issue by denysvitali** [gokrazy/gokrazy#277]
Currently Gokrazy uses templates to render the UI. To allow extensibility, Gokrazy should have an authenticated /api endpoint that can be used to fetch information about the device.

- Board Info
- List of services with their status
- Network info
- CPU / Memory status

With such an API, it would be easier to manage all the Gokrazy instances and see the services status.

My use case: using an Android app to manage my N gokrazy instances

**Comment by stapelberg** [comment]
Hey @denysvitali 

gokrazy does in fact already have such an API (though we should probably document it better).

See https://github.com/gokrazy/gokrazy/blob/76f798eace029442d73f52aac02e6c70bc13e1cb/status.go#L266 and https://github.com/gokrazy/gokrazy/blob/76f798eace029442d73f52aac02e6c70bc13e1cb/status.go#L441

Also note that GUS (gokrazy update service) contains a dashboard of gokrazy instances that are configured to heartbeat to GUS, which makes for a nice overview. Here’s how my instance looks like:

![2024-08-25-gus](https://github.com/user-attachments/assets/7f356624-e86f-4d2c-a1b5-130560a6ffab)

Regarding CPU / memory utilization and so on, that’d probably be better exported from https://github.com/gokrazy/stat

**Comment by denysvitali** [comment]
Nice! I totally missed the JSON part. That's neat!

I think I have everything I need for now to start drafting an implementatiom of a companion app. This in fact confirms that GoKrazy has an API for everything I mentioned above
