### ISSUE TITLE
PATH, GOROOT, GOPATH

### ISSUE THREAD

**Issue by YaguraStation** [gokrazy/gokrazy#28]
I am sure there is a simpler and more elegant way of handling things than I am currently doing. And it probably should be referenced in the README.md somewhere, but what is best practice when using `gokr-packer` with `sudo `in regards to environment variables?

**Comment by stapelberg** [comment]
The best practice is to not use sudo at all, but rather grant the required capabilities to the gokr-packer binary, as https://gokrazy.org/quickstart.html does via `sudo setcap CAP_SYS_ADMIN,CAP_DAC_OVERRIDE=ep $(go env GOPATH)/bin/gokr-packer`.

Why does that not work for you?

**Comment by YaguraStation** [comment]
TLDR: That simply answers the question, sorry. 

It's a long - now uninteresting story - from my first experiment with `gokrazy`, setting an environment up for _root_, then reverting back to user and messed up `secure_path` and `env_keep` in the sudoers file... eventually libcap2-bin not working anymore. Probably based on some initial misunderstanding of a few errors, the role of setcap, and necessity of elevated rights. Works on a "clean" machine just fine now.

**Comment by tv42** [comment]
Permanently giving some random binary `CAP_SYS_ADMIN` is a really bad idea. That allows it to e.g. extract secrets from from kernel memory and from disk. Transient privileges (for this run only) are much safer.

**Comment by stapelberg** [comment]
How exactly can one grant transient privileges?

**Comment by tv42** [comment]
You're already doing that with sudo, for the setcap run.

**Comment by stapelberg** [comment]
Using sudo for the gokr-packer command results in compilation happening as root, which is not intended.

If you dislike granting CAP_SYS_ADMIN, don’t specify a privileged device to the -overwrite= flag and do your own copying.

**Comment by tv42** [comment]
Sounds like a great reason to separate building from writing to SD card. *shrug* If this doesn't seem important to you, I'll just have to take note that you don't care and move along.
