### ISSUE TITLE
Use a randomly generated password by default

### ISSUE THREAD

**Issue by Chaz6** [gokrazy/gokrazy#37]
Please make the image use a random password generated at write time instead of a common password known to potential attackers. Default passwords are the source of multiple CVE's and seems at odds with the primary goal of reducing attack surface.

**Comment by stapelberg** [comment]
What makes you think we use a common password? We already generate a password the first time you use gokrazy.

**Comment by Chaz6** [comment]
A quote from the page at https://gokrazy.org/quickstart.html:-

```
To interact with the device, gokrazy provides a web interface reachable at:

	http://gokrazy:secretpw@gokrazy/
```

There is no indication that it generates a random password anywhere on the page currently.

**Comment by YaguraStation** [comment]
I think for anybody who actually ran `gokr-packer` IRL, this was always very clear.

**Comment by Chaz6** [comment]
Great thanks!

**Comment by stapelberg** [comment]
Done with https://github.com/gokrazy/gokrazy.github.io/commit/4a6852ccda7d4271a2dc5fef438ad01fa1c96deb
