### ISSUE TITLE
Avoid passwords on command-line

### ISSUE THREAD

**Issue by tv42** [gokrazy/gokrazy#38]
From https://github.com/gokrazy/gokrazy

    gokr-packer -update=http://gokrazy:mysecretpassword@gokrazy/ github.com/gokrazy/hello

That's a bad example, encouraging bad habits in people. You can do better than that!

**Comment by stapelberg** [comment]
What’s the bad habit you’re alluding to?

**Comment by tv42** [comment]
Passwords on command-line.

**Comment by stapelberg** [comment]
Let me ask more directly: what is bad about specifying passwords on the command-line?

**Comment by tv42** [comment]
They're visible to all processes running on the host.
