### ISSUE TITLE
Examples refer to private repo https://github.com/stapelberg/mediaserver

### ISSUE THREAD

**Issue by tv42** [gokrazy/gokrazy#39]
https://github.com/gokrazy/gokrazy

```
gokr-packer \
  -overwrite_init=$(go env GOPATH)/src/github.com/stapelberg/mediaserver/cmd/init/init.go \
  github.com/gokrazy/hello
```

(Note that the package must result in a binary called “init”.)

Then, edit the github.com/stapelberg/mediaserver package to your liking. When done, pack an image with your own init package:

```
gokr-packer \
  -init_pkg=github.com/stapelberg/mediaserver \
  -overwrite=/dev/sdb \
  github.com/gokrazy/hello
```

That repo is private/non-existent.

**Comment by stapelberg** [comment]
Yeah, it’s a placeholder for the repo name of the application you’d like to create on gokrazy.

**Comment by tv42** [comment]
That's not at all clear from the readme.
