### ISSUE TITLE
platform: add support for the rpi4b

### ISSUE THREAD

**Issue by stapelberg** [gokrazy/gokrazy#48]
The Raspberry Pi 4 was just released: https://www.raspberrypi.org/blog/raspberry-pi-4-on-sale-now-from-35/

I have ordered one to make sure gokrazy works on it.

Update: tracking issues that I have encountered on the Raspberry Pi 4 Model B (rpi4b):

* [x] the UART swap dtb patch needs to be rebased onto the rpi4 dtb file
* [x] the broadcom genet driver needs to be enabled for the eth0 network interface to show up
* [x] The SD card reader currently ends up at `/dev/mmcblk1*`, but should be `/dev/mmcblk0*` for consistency with earlier models.
  * The [Raspberry Pi kernel uses](https://github.com/raspberrypi/linux/blob/a75a01501330a9be188561b0e9da1da6da372eea/drivers/mmc/core/host.c#L368) a [kernel patch](https://www.spinics.net/lists/linux-mmc/msg36704.html) for mmc numbering based on devicetree aliases, but the patch has been declined for upstream inclusion.
  * Side note: this wouldn’t be a problem if we would use `UUID=` to specify the root device, but those require booting with an initrd, which is something I’d like to avoid for as long as possible.
  * We’re now using `PARTUUID=`, which is understood by the kernel and does not require an initrd: see issue #52 
* [x] network interface: interface detected and link status shown as up, but device does not respond to IPv6 link-local pings or fetch an IP address via DHCPv4
  * EEPROM version “2019-09-10 - Git f626c772” contains the only ethernet change, but it might be relevant: “Configure ethernet RGMII pins at power on. This is a minor change which which may improve reliability of ethernet for some users.”.
  * In my tests, updating to the latest rpi-eeprom (git commit a5be2ff8b15dd36cb3bb83a3f864514cd9cfcf3e) helped a bit (the device picks an IPv6 address based on router advertisements), but I still can’t get ethernet to work.
  * posted https://github.com/lategoodbye/rpi-zero/issues/47
  * fixed by setting `phy-mode` to `rgmii`
* [x] include Raspberry Pi 4 firmware files (start4*, fixup4*)
* [x] USB ports don’t work
  * the xhci_hcd driver is enabled (CONFIG_USB_XHCI_HCD=y), but doesn’t enumerate any devices at boot
* [x] set up an rpi4 in continuous integration
* [x] include eeprom updates (gokrazy/rpi-eeprom for consistency? or just include in firmware?)
  * background info: https://news.ycombinator.com/item?id=21674550
  * [x] set up GitHub actions CI to pull in new EEPROM versions
  * [x] packer: ensure filenames match the updater pattern
  * [x] display the eeprom version by reading pieeprom.sig and vl805.sig when `RECOVERY.00*` is present (= last update succeeded)
  * [x] <s>skip updates when the EEPROM is already up-to-date</s> Update: I have verified that the bootloader skips EEPROM updates when the EEPROM is already up to date: https://user-images.githubusercontent.com/55506/85105058-10d47e80-b20a-11ea-8d13-5caa8ad961c3.jpg
* [x] update issue template
* [x] update website
* [x] update README.md
* [x] update gokr-packer message
* [x] repo descriptions

**Comment by stapelberg** [comment]
We’re currently blocked on https://github.com/raspberrypi/linux/issues/3032 (arm64 kernel support for the Pi 4 being in early stages).

Not sure which patches are required to make this work.

**Comment by stapelberg** [comment]
To summarize progress on the referenced issue: when manually placing the dtb file, armstub and raspberrypi/linux kernel image on the SD card, and limiting the memory to 1G, I can get some output on the serial console.

I can’t get an upstream kernel to print anything on the serial console, though.

I suppose it’ll be a while before the necessary changes are upstreamed.

**Comment by vianpl** [comment]
> To summarize progress on the referenced issue: when manually placing the dtb file, armstub and raspberrypi/linux kernel image on the SD card, and limiting the memory to 1G, I can get some output on the serial console.
> 
> I can’t get an upstream kernel to print anything on the serial console, though.
> 
> I suppose it’ll be a while before the necessary changes are upstreamed.

Can you try adding gpu_freq=500 to config.txt? AFAIK the VPU clock and UART are derived from the same PLL and I suspect the firmware may be altering the frequencies behind your back.

**Comment by stapelberg** [comment]
Side note: dividuum described how to do firmware updates at https://news.ycombinator.com/item?id=21674550, which is important for better thermals and power usage: https://www.raspberrypi.org/blog/thermal-testing-raspberry-pi-4/

**Comment by stapelberg** [comment]
https://github.com/lategoodbye/rpi-zero/issues/43 has a good overview of the current status. Looks like Linux 5.6 can be the earliest we could possibly see good-enough support.

**Comment by stapelberg** [comment]
The EEPROM updates are now in place, and I have been using a Pi 4 to develop and to run my home automation for weeks without any trouble.

Hence, the Pi 4 is now officially a target platform of https://gokrazy.org/!
