### ISSUE TITLE
remote syslog support as a platform feature

### ISSUE THREAD

**Issue by stapelberg** [gokrazy/gokrazy#50]
Currently, individual apps need to implement remote syslog themselves. It would be nice to just `echo 10.0.0.76:514 > /perm/remote_syslog/target` and have stdout/stderr of all apps copied to that location.

**Comment by stapelberg** [comment]
I have an implementation of this, will test some more and push tomorrow.

**Comment by prologic** [comment]
I hope you will update some docs somewhere to show how to use this? :)

**Comment by stapelberg** [comment]
Instructions are in the commit message for now. We don’t really have a proper documentation place yet, will think about how to address this.
