### ISSUE TITLE
localtime symlink misspelled 

### ISSUE THREAD

**Issue by r0l1** [gokrazy/gokrazy#55]
https://github.com/gokrazy/gokrazy/blob/f3445e01a904ba7991a38651de02701c22903b0c/mount.go#L28

**Comment by stapelberg** [comment]
There is no misspelling here, see the comment immediately above it: the code path you’re looking at is for the old FAT root file systems (we have switched to SquashFS in the meantime). On our FAT file system, file names were limited to 8.3, so we actually had `/localtim` :)

**Comment by r0l1** [comment]
Thanks for the clarification. Great project imho.
