### ISSUE TITLE
Outdated documentation about file systems used

### ISSUE THREAD

**Issue by CodeZombieCH** [gokrazy/gokrazy#56]
## Platform

I’m using:

* [x] gokrazy/apu2e4 (router7 on the PC Engines apu2e4, which from my understanding uses gokrazy underneath)

## Observed behavior

Partition 2 and 3 on a recently created new installation of router7 use the **squashfs** file system. 

## Expected behavior

The documentation (see https://github.com/gokrazy/gokrazy#sd-card-contents) describes partition 2 and 3 to use the **FAT16B** file system.

## Conclusion
Looking at the current implementation (see https://github.com/gokrazy/tools/blob/a11ea1b25921d1f2d990d9d2b9b398d879ce4102/cmd/gokr-packer/parttable.go#L31) I think the documentation is outdated.

**Comment by stapelberg** [comment]
It is indeed, thanks for the hint. We switched to SquashFS a while ago.
