### ISSUE TITLE
/proc/net/pnp mounted before /proc?

### ISSUE THREAD

**Issue by rgl** [gokrazy/gokrazy#63]
Shouldn't this:

https://github.com/gokrazy/gokrazy/blob/ffc8928d2e0a357d42c45f5bef1d01cfddbe9490/mount.go#L22-L24

Be done after mounting `/proc` at the following?

https://github.com/gokrazy/gokrazy/blob/ffc8928d2e0a357d42c45f5bef1d01cfddbe9490/mount.go#L77-L85

**Comment by stapelberg** [comment]
Not necessarily, no: it’s a symbolic link, and we don’t follow it to its target before /proc is mounted.
