### ISSUE TITLE
Consider exposing Linux kernel version in web UI

### ISSUE THREAD

**Issue by mdlayher** [gokrazy/gokrazy#66]
## Platform

I’m using:

* [ ] gokrazy/rpi3b
* [ ] gokrazy/rpi3b+
* [x] gokrazy/rpi4b
* [ ] gokrazy/apu2c4
* [ ] gokrazy/x86-64

## Observed behavior

Web UI displays useful information about the currently running system, but no Linux kernel version. There is the "version" string but this only seems to indicate when the system was last updated.

## Expected behavior

Ability to view Linux kernel version without resorting to breakglass:
```
/tmp/breakglass048386764 # uname -a
Linux monitnerr-1 5.7.8 #1 SMP PREEMPT Wed Mar 1 20:57:29 UTC 2017 aarch64 GNU/Linux
```

**Comment by stapelberg** [comment]
Definitely a good idea. Pull requests welcome :)

**Comment by mdlayher** [comment]
Will do later today!
