### ISSUE TITLE
How to handle logging?

### ISSUE THREAD

**Issue by hazcod** [gokrazy/gokrazy#71]
Hi, what is the desired way to 1) send logs (stdout/stderr?) and 2) to consume?
I understand there is the serial connector, but I am unsure on how to send text via that.

**Comment by stapelberg** [comment]
stdout/stderr are exposed via the web interface.

Please see https://www.youtube.com/watch?v=1g46ei9aBH0 to get a feel for gokrazy if you’re not in a position to try it out yourself.

**Comment by hazcod** [comment]
Thank you for the work @stapelberg , i'm investigating gokrazy at this moment so will order a Pi4 soon.
