### ISSUE TITLE
Question: Can we use gokrazy in commercial Iot implementations?

### ISSUE THREAD

**Issue by plkumar** [gokrazy/gokrazy#89]
Can we use gokrazy in commercial Iot implementations?

**Comment by stapelberg** [comment]
It’s an open source project, so nobody is stopping you from using it in any way you see fit :)

That said, there is no guaranteed support, no guarantee that any features you might want to add will be merged, and no warranty whatsoever for any problems that might arise.

Can you share more details about what your project is?

**Comment by sandrolino** [comment]
Are you aware of any companies using gokrazy in production?
I'm working for a startup doing flexibility aggregation for EVs and large roof-top solar systems (it's different from EVCC) and would love to use it. Having experience from other starutps(companies would make the evaluation easier (besides own testing of course).

**Comment by stapelberg** [comment]
I am not aware of any company using gokrazy in production.
