### ISSUE TITLE
Question: How to store different setups?

### ISSUE THREAD

**Issue by christian-heusel** [gokrazy/gokrazy#92]
Hey gokrazy contributors! ❤️ 
I am just getting started with the toolchain, but having great fun exploring so far. 😊 

How would I store different setups? Should i do this via a shell skript where store the different options like in the following snippets or is there a better way?

`raspi1-config.sh`
```bash
#!/bin/bash

GOKRAZY_UPDATE=http://gokrazy:redacted@gokrazy/ gokr-packer \
  github.com/gokrazy/hello \
  github.com/gokrazy/serial-busybox \
  github.com/gokrazy/breakglass
``` 
`raspi2-config.sh`
```bash
#!/bin/bash

GOKRAZY_UPDATE=http://gokrazy:redacted@gokrazy/ gokr-packer \
  -serial_console=disabled \
  github.com/gokrazy/fbstatus \      
  github.com/gokrazy/hello \   
  github.com/gokrazy/serial-busybox
```

**Comment by stapelberg** [comment]
Welcome! 👋

Yes, persisting your gokr-packer command lines is a good first step. In router7, I’m using a Makefile with a factored out package list (see https://github.com/rtr7/router7/blob/master/Makefile#L3), but you’re free to use whichever mechanism is most convenient for you.

The other recommendation (from https://gokrazy.org/quickstart/) is to create one directory per gokrazy instance (with their own go.mod/go.sum files). For example, I have ~/gokrazy/scan2drive, ~/gokrazy/dr, etc. In each directory, I can run `make update`.

**Comment by stapelberg** [comment]
Assuming the question is answered :)
